# distributed setting
distributed: False

# amp parameters
apex_amp: False
native_amp: False

# model parameters
model: resnet50
replace_relu_with_gelu: False
num_classes: 1000
resume: ''
pretrain: './outputs/finetune_resnet_relu/2024-02-01_16-29-25/checkpoint-3.pth.tar'
gp: null
channels_last: False

# Batch norm parameters
bn_momentum: null
bn_eps: null
sync_bn: False
dist_bn: reduce
split_bn: False

# optimizer parameters
opt: adamw
opt_eps: 1.0e-8
opt_betas: null
momentum: 0.9
weight_decay: 0.05
clip_grad: 1.0
clip_mode: norm
layer_decay: null

# lr schedule
epochs: 50
sched: cosine
lrb: 0.625e-3
lr: null
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
lr_cycle_mul: 1.0
lr_cycle_decay: 0.5
lr_cycle_limit: 1
lr_k_decay: 1.0
warmup_lr: 1.0e-6
min_lr: 1.0e-5
epoch_repeats: 0
start_epoch: null
decay_epochs: 15
warmup_epochs: 5
cooldown_epochs: 0
patience_epochs: 0
decay_rate: 0.1

# dataset parameters
batch_size: 64
grad_accum: 1
train_dir: /data/vision/torralba/datasets/imagenet_pytorch/train
eval_dir: /data/vision/torralba/datasets/imagenet_pytorch/val
input_size: 224
crop_pct: 0.875
interpolation: bicubic
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]

# augmentation
no_aug: False
color_jitter: 0.4
aa: rand-m9-mstd0.5-inc1
aug_repeats: 0
aug_splits: 0
jsd_loss: False
# random erase
reprob: 0.25
remode: pixel
recount: 1
resplit: False
mixup: 0.8
cutmix: 1.0
cutmix_minmax: null
mixup_prob: 1.0
mixup_switch_prob: 0.5
mixup_mode: batch
mixup_off_epoch: 0
smoothing: 0.1
train_interpolation: bicubic
# drop connection
drop: 0.0
drop_path: 0.0
drop_block: null

# ema
model_ema: True
model_ema_force_cpu: False
model_ema_decay: 0.9998

# misc
seed: 0
log_interval: 50
recovery_interval: 0
num_workers: 6
output_dir: 'outputs/gradnorm_resnet_relu'
save_log: save_log.txt
eval_metric: advloss
pin_mem: True

# advtrain
advtrain: False
attack_criterion: mixup

# gradnorm
gradnorm: True
loss_fn: 'DBP'
ce_weight: 0.5
gradnorm_weight: 0.5
alpha: [0.0, 0.1, 1.0]
alpha_start_epoch: 0

# saving snapshots
save_snapshot_for_inference: ['0;100', '1;0', '1;50', '1;100', '1;150', '1;200', '1;500', '1;1000', '1;2000', '1;5000', '2;5003', '5;5003', '10;5003', '15;5003', '20;5003']
collect_gradient_statistics: [0,1]